---
- name: install java
  apt:
    name: default-jre
    state: present

- name: download data
  get_url:
    url: https://raw.githubusercontent.com/paulduchesne/australian-filmography/main/data/merge/merge.ttl
    dest: '/home/{{ vm_username }}/data.ttl'

- name: pull jena
  become: yes
  become_user: '{{ vm_username}}'
  unarchive:
    src: https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-4.5.0.tar.gz
    dest: '/home/{{ vm_username }}/'
    remote_src: yes

- name: launch jena
  command: './fuseki-server --file=/home/{{ vm_username }}/data.ttl /filmography'
  become: yes
  become_user: '{{ vm_username}}'
  args:
    chdir: '/home/{{ vm_username }}/apache-jena-fuseki-4.5.0/'


